
# Excluded - swiftlint don't checking!

excluded:
  - "Pods"
  - "*.generated.swift"


# Disabled rules - deactivating.

disabled_rules:
  - todo
  - force_cast
  - reduce_boolean
  - vertical_whitespace
  - trailing_whitespace
  - valid_ibinspectable
  - switch_case_alignment
  - notification_center_detachment
  - multiple_closures_with_trailing_closure


# Optional rules - activating.

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - implicit_return
  - force_unwrapping
  - multiline_parameters
  - overridden_super_call
  - redundant_nil_coalescing
  - operator_usage_whitespace
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument


# Setting standard rules.
# ** - It is necessary to correct in the code and move the boundaries downward.

file_length:
  warning: 600
  error: 800

line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_comments: true

type_body_length:
  warning: 400
  error: 500

function_body_length:
  warning: 40
  error: 60

type_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 60
    error: 80
  allowed_symbols: "_"
  excluded:
    - iPhone
    - iPad
    - T

identifier_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 80
    error: 80
  allowed_symbols: "_"
  validates_start_with_lowercase: false
  excluded:
    - x
    - y
    - a
    - b
    - c
    - p
    - v

large_tuple:
  warning: 4
  error: 5

function_parameter_count:
  error: 7

nesting:
  type_level:
    warning: 3

cyclomatic_complexity:
  warning: 10
  error: 40
  ignores_case_statements: true

unneeded_parentheses_in_closure_argument:
  severity: error

vertical_parameter_alignment_on_call:
  severity: error

redundant_optional_initialization:
  severity: error

vertical_parameter_alignment:
  severity: error

redundant_discardable_let:
  severity: error

operator_usage_whitespace:
  severity: error

redundant_nil_coalescing:
  severity: error

unneeded_break_in_switch:
  severity: error

return_arrow_whitespace:
  severity: error

unused_optional_binding:
  severity: error

overridden_super_call:
  severity: error

multiline_parameters:
  severity: error

operator_whitespace:
  severity: error

leading_whitespace:
  severity: error

statement_position:
  severity: error

control_statement:
  severity: error

trailing_newline:
  severity: error

force_unwrapping:
  severity: error

implicit_return:
  severity: error

syntactic_sugar:
  severity: error

implicit_getter:
  severity: error

closure_spacing:
  severity: error

opening_brace:
  severity: error

explicit_init:
  severity: error

weak_delegate:
  severity: error

empty_count:
  severity: error

colon:
  severity: error

comma:
  severity: error

mark:
  severity: error


# Custom rules - creating.

custom_rules:
  comments_space:
    regex: '(^ *//\w+)'
    message: "There should be a space after '//'."
    severity: error

  class_protocol:
    regex: ': class '
    message: "Use 'Anyobject' instead."
    severity: error

  final_class:
    regex: '^class'
    message: "All classes must be final or nonfinal."
    severity: error

  unnecessary_type:
    regex: '[ a-zA-Z0-9]*(?:let|var) [ a-zA-Z0-9]*: ([a-zA-Z0-9]*)[ ]*= \1(\.|\(){1}'
    message: "Type Definition Not Needed."
    severity: error

  empty_closure_params:
    regex: '\{ (\(\) -> Void in)$'
    message: "`() -> Void in` should be avoided."
    severity: error
